CREATE TABLE STUDENT(
        ID        SERIAL PRIMARY KEY,
        LASTNAME  CHAR(35) NOT NULL DEFAULT 'DUPOND',
        FIRSTNAME CHAR(35) NOT NULL DEFAULT 'MonsieurMadame',
        AGE       NUMERIC(3) NOT NULL DEFAULT 99,
        CONSTRAINT STUDENT_ID_0 PRIMARY KEY (ID)
);          
CREATE TABLE GRADE(
        ID        SERIAL,
        STUDENT_ID INTEGER NOT NULL,
        COURSE_ID INTEGER NOT NULL,
        GRADE     NUMERIC(3,1) NOT NULL DEFAULT 1.23,
         FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
         FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);
CREATE TABLE COURSE(
        ID        SERIAL PRIMARY KEY,
        LABEL      CHAR(35) NOT NULL DEFAULT 'Manquant',
        COEF       NUMERIC(3,1) NOT NULL DEFAULT 1,
);






